export interface InstitutionData {
  name: string;
  type: string;
  description: string;
  website?: string;
  location?: string;
  stages?: Array<"Ide" | "Awal" | "Berkembang">;
  requirements?: string;
  minAmount?: string;
  maxAmount?: string;
  applyLink?: string;
  contact?: {
    email?: string;
    phone?: string;
  };
}

export const ventureCapitalFirms: InstitutionData[] = [
  {
    name: "East Ventures",
    type: "Venture Capital",
    description: "Fokus pada startup tahap awal dan pertumbuhan di Asia Tenggara, termasuk fintech, e-commerce, dan SaaS.",
    website: "https://east.vc",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Pitch deck, traction pengguna, dan strategi ekspansi regional.",
    minAmount: "Rp 7,5 miliar",
    maxAmount: "Rp 75 miliar",
    applyLink: "https://east.vc/contact",
    contact: { email: "info@east.vc" },
  },
  {
    name: "Alpha JWC Ventures",
    type: "Venture Capital",
    description: "Investasi tahap awal dan tahap pertumbuhan untuk perusahaan teknologi di Indonesia dan Asia Tenggara.",
    website: "https://www.alphajwc.com",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Tim yang kuat, model bisnis digital, dan pertumbuhan pelanggan yang terbukti.",
    minAmount: "Rp 15 miliar",
    maxAmount: "Rp 120 miliar",
    applyLink: "https://www.alphajwc.com/contact",
    contact: { email: "hello@alphajwc.com" },
  },
  {
    name: "AC Ventures",
    type: "Venture Capital",
    description: "Dana ventura yang berfokus pada founder dan startup teknologi di Indonesia sejak tahap awal hingga skala.",
    website: "https://ac.vc",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Unit economics kuat, tim solid, dan daya saing global.",
    minAmount: "Rp 11 miliar",
    maxAmount: "Rp 150 miliar",
    applyLink: "https://ac.vc/contact",
    contact: { email: "info@ac.vc" },
  },
  {
    name: "Intudo Ventures",
    type: "Venture Capital",
    description: "VC yang mendukung startup yang melayani massa besar di Indonesia dengan fokus sektor konsumer dan teknologi.",
    website: "https://www.intudovc.com",
    location: "Jakarta",
    stages: ["Ide", "Awal"],
    requirements: "Ide dengan potensi pasar besar, tim lokal, dan strategi monetisasi jelas.",
    minAmount: "Rp 3,75 miliar",
    maxAmount: "Rp 30 miliar",
    applyLink: "https://www.intudovc.com/contact",
    contact: { email: "hello@intudovc.com" },
  },
  {
    name: "MDI Ventures",
    type: "Corporate Venture Capital",
    description: "Divisi modal ventura Telkom Indonesia, berinvestasi di startup teknologi yang mendukung digitalisasi.",
    website: "https://mdi.ventures",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Solusi teknologi yang dapat terintegrasi dengan ekosistem digital Telkom.",
    minAmount: "Rp 7,5 miliar",
    maxAmount: "Rp 225 miliar",
    applyLink: "https://mdi.ventures/contact",
    contact: { email: "contact@mdi.ventures" },
  },
  {
    name: "Kejora Ventures",
    type: "Venture Capital",
    description: "Fokus pada pendanaan tahap awal untuk perusahaan teknologi konsumer, fintech, dan marketplace.",
    website: "https://kejora.vc",
    location: "Jakarta",
    stages: ["Ide", "Awal"],
    requirements: "Startup dengan solusi konsumer inovatif dan potensi skalabilitas cepat.",
    minAmount: "Rp 3,75 miliar",
    maxAmount: "Rp 60 miliar",
    applyLink: "https://kejora.vc/contact",
    contact: { email: "hello@kejora.vc" },
  },
  {
    name: "Convergence Ventures",
    type: "Venture Capital",
    description: "Investasi dalam startup teknologi Indonesia yang siap berkembang di pasar lokal dan regional.",
    website: "https://www.convergencevc.com",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Bukti permintaan pasar, pertumbuhan pengguna, dan model bisnis terukur.",
    minAmount: "Rp 7,5 miliar",
    maxAmount: "Rp 90 miliar",
    applyLink: "https://www.convergencevc.com/contact",
    contact: { email: "contact@convergencevc.com" },
  },
  {
    name: "Venturra Capital",
    type: "Venture Capital",
    description: "VC yang berinvestasi di startup tahap awal dan growth stage di Asia Tenggara, dengan portofolio Indonesia kuat.",
    website: "https://venturra.com",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Perusahaan teknologi dengan strategi ekspansi regional dan tim founder kuat.",
    minAmount: "Rp 15 miliar",
    maxAmount: "Rp 120 miliar",
    applyLink: "https://venturra.com/contact",
    contact: { email: "hello@venturra.com" },
  },
  {
    name: "Openspace Ventures",
    type: "Venture Capital",
    description: "Perusahaan modal ventura regional yang mendukung startup teknologi di Asia Tenggara, termasuk Indonesia.",
    website: "https://openspace.vc",
    location: "Jakarta",
    stages: ["Ide", "Awal", "Berkembang"],
    requirements: "Inovasi digital, tim global, dan potensi pertumbuhan lintas negara.",
    minAmount: "Rp 7,5 miliar",
    maxAmount: "Rp 180 miliar",
    applyLink: "https://openspace.vc/contact",
    contact: { email: "hello@openspace.vc" },
  },
  {
    name: "Agaeti Ventures",
    type: "Venture Capital",
    description: "Mendukung startup Indonesia di sektor e-commerce, fintech, marketplace, dan SaaS.",
    website: "https://agaetiventures.com",
    location: "Jakarta",
    stages: ["Ide", "Awal"],
    requirements: "Founder lokal dengan ide digital yang siap diuji pasar.",
    minAmount: "Rp 1,5 miliar",
    maxAmount: "Rp 30 miliar",
    applyLink: "https://agaetiventures.com/contact",
    contact: { email: "info@agaetiventures.com" },
  },
];

export const financingInstitutions: InstitutionData[] = [
  {
    name: "Bank Rakyat Indonesia (BRI)",
    type: "Bank BUMN",
    description: "Menyediakan KUR, Kredit Usaha Rakyat, kredit mikro, dan program pembiayaan UMKM dengan jaringan luas.",
    website: "https://bri.co.id",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "NIB, KTP, NPWP, laporan keuangan, dan rencana penggunaan dana.",
    minAmount: "Rp 10 juta",
    maxAmount: "Rp 500 juta",
    applyLink: "https://bri.co.id/pembiayaan-umkm",
    contact: { phone: "+62 21 2550 0000" },
  },
  {
    name: "Bank Negara Indonesia (BNI)",
    type: "Bank BUMN",
    description: "Menawarkan KUR, kredit modal kerja, dan fasilitas pembiayaan UMKM dengan dukungan digital.",
    website: "https://bni.co.id",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "KTP, usaha berjalan, rekening bank, dan dokumen legalitas usaha.",
    minAmount: "Rp 10 juta",
    maxAmount: "Rp 500 juta",
    applyLink: "https://bni.co.id/umkm",
    contact: { phone: "+62 21 2300 3000" },
  },
  {
    name: "Bank Mandiri",
    type: "Bank BUMN",
    description: "Memberikan produk pembiayaan UMKM, modal kerja, dan pembiayaan investasi untuk usaha kecil dan menengah.",
    website: "https://bankmandiri.co.id",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Dokumen usaha, rencana penggunaan modal, dan kemampuan bayar yang jelas.",
    minAmount: "Rp 25 juta",
    maxAmount: "Rp 1 miliar",
    applyLink: "https://bankmandiri.co.id/umkm",
    contact: { phone: "+62 21 5299 7777" },
  },
  {
    name: "Permodalan Nasional Madani (PNM)",
    type: "Lembaga Pembiayaan Pemerintah",
    description: "Menyediakan pembiayaan Mikro, Mekaar, dan ULaMM untuk usaha mikro dan kecil di seluruh Indonesia.",
    website: "https://www.pnm.co.id",
    location: "Jakarta",
    stages: ["Ide", "Awal"],
    requirements: "Usaha mikro, rencana usaha sederhana, dan partisipasi dalam program pemberdayaan.",
    minAmount: "Rp 2 juta",
    maxAmount: "Rp 100 juta",
    applyLink: "https://www.pnm.co.id/mekaar",
    contact: { phone: "+62 21 2278 8000" },
  },
  {
    name: "Lembaga Pengelola Dana Bergulir (LPDB-KUMKM)",
    type: "Lembaga Pemerintah",
    description: "Memberikan pinjaman bergulir untuk koperasi dan UMKM dengan suku bunga kompetitif.",
    website: "https://lpdb.kemenkopukm.go.id",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Koperasi/UMKM resmi, proposal usaha, dan rencana penggunaan dana.",
    minAmount: "Rp 100 juta",
    maxAmount: "Rp 5 miliar",
    applyLink: "https://lpdb.kemenkopukm.go.id/contact",
    contact: { email: "info@lpdb.kemenkopukm.go.id" },
  },
  {
    name: "Pegadaian",
    type: "Badan Usaha Milik Negara",
    description: "Memberikan pembiayaan gadai mikro, kredit usaha rakyat, dan solusi modal kerja berbasis aset.",
    website: "https://www.pegadaian.co.id",
    location: "Jakarta",
    stages: ["Ide", "Awal"],
    requirements: "Aset jaminan, identitas yang valid, dan usaha aktif.",
    minAmount: "Rp 1 juta",
    maxAmount: "Rp 200 juta",
    applyLink: "https://www.pegadaian.co.id/kredit-umkm",
    contact: { phone: "+62 21 8064 8888" },
  },
  {
    name: "KoinWorks",
    type: "Fintech P2P Lending",
    description: "Platform pendanaan peer-to-peer yang menyediakan pinjaman modal usaha untuk UMKM dan pelaku usaha kecil.",
    website: "https://koinworks.com",
    location: "Jakarta",
    stages: ["Ide", "Awal"],
    requirements: "Riwayat usaha, dokumen identitas, dan target penggunaan dana yang jelas.",
    minAmount: "Rp 2 juta",
    maxAmount: "Rp 200 juta",
    applyLink: "https://koinworks.com/umkm",
    contact: { email: "support@koinworks.com" },
  },
  {
    name: "Investree",
    type: "Fintech P2P Lending",
    description: "Menyediakan pembiayaan invoice financing, pinjaman modal kerja, dan pendanaan usaha digital.",
    website: "https://investree.id",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Invoice atau piutang usaha, usaha minimal 6 bulan, dan laporan keuangan dasar.",
    minAmount: "Rp 25 juta",
    maxAmount: "Rp 2 miliar",
    applyLink: "https://investree.id/umkm",
    contact: { email: "support@investree.id" },
  },
  {
    name: "Amartha",
    type: "Fintech P2P Lending",
    description: "Fokus pada pembiayaan inklusif untuk perempuan pelaku usaha mikro di desa dan komunitas perkotaan.",
    website: "https://amartha.com",
    location: "Jakarta",
    stages: ["Ide", "Awal"],
    requirements: "Usaha mikro yang jelas, profil usaha, dan fokus sosial positif.",
    minAmount: "Rp 1 juta",
    maxAmount: "Rp 50 juta",
    applyLink: "https://amartha.com/umkm",
    contact: { email: "info@amartha.com" },
  },
  {
    name: "Kredivo",
    type: "Fintech Kredit Konsumen",
    description: "Menyediakan pembayaran cicilan dan pinjaman modal usaha kecil di platform digital.",
    website: "https://www.kredivo.com",
    location: "Jakarta",
    stages: ["Ide", "Awal"],
    requirements: "KTP, informasi kredit, dan penggunaan dana yang produktif.",
    minAmount: "Rp 500 ribu",
    maxAmount: "Rp 50 juta",
    applyLink: "https://www.kredivo.com/business",
    contact: { email: "support@kredivo.com" },
  },
  {
    name: "BTPN",
    type: "Bank",
    description: "Menghadirkan solusi perbankan mikro dan pembiayaan UKM melalui BTPN Wow! dan kredit usaha kecil.",
    website: "https://www.btpn.com",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Usaha UMKM, rekening bank, dan kesiapan pelatihan finansial.",
    minAmount: "Rp 5 juta",
    maxAmount: "Rp 250 juta",
    applyLink: "https://www.btpn.com/umkm",
    contact: { phone: "+62 21 2960 8000" },
  },
  {
    name: "Bank Syariah Indonesia (BSI)",
    type: "Bank Syariah",
    description: "Menawarkan pembiayaan UMKM berbasis syariah, modal kerja, dan akad yang sesuai ekonomi umat.",
    website: "https://www.bsi.co.id",
    location: "Jakarta",
    stages: ["Awal", "Berkembang"],
    requirements: "Usaha syariah, dokumen legalitas, dan rencana penggunaan dana sesuai prinsip syariah.",
    minAmount: "Rp 10 juta",
    maxAmount: "Rp 250 juta",
    applyLink: "https://www.bsi.co.id/umkm",
    contact: { phone: "+62 21 500 047" },
  },
];
